<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CsWin32Generator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.csproj" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>